require:
  - rubocop-rails

AllCops:
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*"
    # 以下デフォルト
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
  NewCops: enable # 新規追加のPendingCopsを有効化

# コメントをスペースで揃えるのを許す
Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

# メソッド名のエイリアスをつけるときは"alias"を使い、"alias_method"は使わない
# aliasの方が自由度は低いが安全であるため
Style/Alias:
  EnforcedStyle: prefer_alias

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# Cookpad Styleguideに従い、eachなどの手続き型スタイルではdo/endを、mapなどの関数型スタイルでは{}を使う
# 1ライナーで{}の使用を許可する
Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true

# ドキュメント無しを許可
Style/Documentation:
  Enabled: false

# 先頭行のfrozen stringマジックコメントはなしでもよい
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッド呼び出しのカッコの省略を禁止
Style/MethodCallWithArgsParentheses:
  Enabled: true

# 文字列はダブルクオート
Style/StringLiterals:
  EnforcedStyle: double_quotes
